-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 12:37:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basepanav3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basepanav3
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `basepanav3` DEFAULT CHARACTER SET utf8 ;
USE `basepanav3` ;

-- -----------------------------------------------------
-- Table `basepanav3`.`referencias_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`referencias_almacen` (
  `idReferencias_Almacen` INT(11) NOT NULL,
  `Medida` VARCHAR(45) NULL DEFAULT NULL,
  `Cantidad_medida` DECIMAL(10,5) NULL DEFAULT NULL,
  `Tipo_medicion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idReferencias_Almacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`provedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`provedores` (
  `idProvedores` INT(11) NOT NULL,
  `Nombre_provedor` VARCHAR(80) NOT NULL,
  `Producto` VARCHAR(80) NOT NULL,
  `Telefono` VARCHAR(11) NOT NULL,
  `Telefono_opcional` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProvedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`almacen` (
  `idAlmacen` INT(11) NOT NULL,
  `Nombre_Materia` VARCHAR(45) NOT NULL,
  `Cantidad_Existente` DECIMAL(10,5) NOT NULL,
  `Cantidad_Minimas` DECIMAL(10,5) NOT NULL,
  `imagen_ref` VARCHAR(200) NULL DEFAULT NULL,
  `Referencias_Almacen_idReferencias_Almacen` INT(11) NOT NULL,
  `provedores_idProvedores` INT(11) NOT NULL,
  PRIMARY KEY (`idAlmacen`, `Referencias_Almacen_idReferencias_Almacen`, `provedores_idProvedores`),
  INDEX `fk_Almacen_Referencias_Almacen1_idx` (`Referencias_Almacen_idReferencias_Almacen` ASC) ,
  INDEX `fk_almacen_provedores1_idx` (`provedores_idProvedores` ASC) ,
  CONSTRAINT `fk_Almacen_Referencias_Almacen1`
    FOREIGN KEY (`Referencias_Almacen_idReferencias_Almacen`)
    REFERENCES `basepanav3`.`referencias_almacen` (`idReferencias_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almacen_provedores1`
    FOREIGN KEY (`provedores_idProvedores`)
    REFERENCES `basepanav3`.`provedores` (`idProvedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `username` VARCHAR(30) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `status_message` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `last_active` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_groups_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_groups_users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `auth_groups_users_user_id_foreign` (`user_id` ASC) ,
  CONSTRAINT `auth_groups_users_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_identities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_identities` (
  `id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `secret` VARCHAR(255) NOT NULL,
  `secret2` VARCHAR(255) NULL DEFAULT NULL,
  `expires` DATETIME NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `force_reset` TINYINT(1) NOT NULL DEFAULT 0,
  `last_used_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_secret` (`type` ASC, `secret` ASC) ,
  INDEX `user_id` (`user_id` ASC) ,
  CONSTRAINT `auth_identities_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_logins` (
  `id` INT(11) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `id_type` VARCHAR(255) NOT NULL,
  `identifier` VARCHAR(255) NOT NULL,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_type_identifier` (`id_type` ASC, `identifier` ASC) ,
  INDEX `user_id` (`user_id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_permissions_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_permissions_users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `permission` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `auth_permissions_users_user_id_foreign` (`user_id` ASC) ,
  CONSTRAINT `auth_permissions_users_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_remember_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_remember_tokens` (
  `id` INT(11) UNSIGNED NOT NULL,
  `selector` VARCHAR(255) NOT NULL,
  `hashedValidator` VARCHAR(255) NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `expires` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `selector` (`selector` ASC) ,
  INDEX `auth_remember_tokens_user_id_foreign` (`user_id` ASC) ,
  CONSTRAINT `auth_remember_tokens_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`auth_token_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`auth_token_logins` (
  `id` INT(11) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `id_type` VARCHAR(255) NOT NULL,
  `identifier` VARCHAR(255) NOT NULL,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_type_identifier` (`id_type` ASC, `identifier` ASC) ,
  INDEX `user_id` (`user_id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`corroborar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`corroborar` (
  `idcorroborar` INT(11) NOT NULL,
  `Fecha_edicion` DATE NOT NULL,
  `Cantidad_cambio_Existente` DECIMAL(10,5) NOT NULL,
  `Cantidad_Existente_Sistema` DECIMAL(10,5) NOT NULL,
  `Almacen_idAlmacen` INT(11) NOT NULL,
  `Almacen_Referencias_Almacen_idReferencias_Almacen` INT(11) NOT NULL,
  PRIMARY KEY (`idcorroborar`, `Almacen_idAlmacen`, `Almacen_Referencias_Almacen_idReferencias_Almacen`),
  INDEX `fk_corroborar_Almacen1_idx` (`Almacen_idAlmacen` ASC, `Almacen_Referencias_Almacen_idReferencias_Almacen` ASC) ,
  CONSTRAINT `fk_corroborar_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen` , `Almacen_Referencias_Almacen_idReferencias_Almacen`)
    REFERENCES `basepanav3`.`almacen` (`idAlmacen` , `Referencias_Almacen_idReferencias_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`empleados` (
  `idEmpleados` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Numero_Telefonico` VARCHAR(10) NULL DEFAULT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmpleados`, `users_id`),
  INDEX `fk_empleados_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_empleados_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`incremento_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`incremento_almacen` (
  `idIncremento_Almacen` INT(11) NOT NULL,
  `Fecha_de_Ingreso` DATE NOT NULL,
  `Cantidad_Ingresada` DECIMAL(10,5) NOT NULL,
  `Almacen_idAlmacen` INT(11) NOT NULL,
  PRIMARY KEY (`idIncremento_Almacen`, `Almacen_idAlmacen`),
  INDEX `fk_Incremento_Almacen_Almacen_idx` (`Almacen_idAlmacen` ASC) ,
  CONSTRAINT `fk_Incremento_Almacen_Almacen`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `basepanav3`.`almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`productos` (
  `idProductos` INT(11) NOT NULL,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Valor_produccion` DECIMAL(10,5) NULL DEFAULT NULL,
  `Valor_Venta` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`sucursales` (
  `idSucursales` INT(11) NOT NULL,
  `NombreSucursal` VARCHAR(70) NOT NULL,
  `Direccion_Sucursal` VARCHAR(80) NULL DEFAULT NULL,
  `Empleados_idEmpleados` INT(11) NOT NULL,
  PRIMARY KEY (`idSucursales`, `Empleados_idEmpleados`),
  INDEX `fk_Sucursales_Empleados1_idx` (`Empleados_idEmpleados` ASC) ,
  CONSTRAINT `fk_Sucursales_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `basepanav3`.`empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`tabla_produccion_fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`tabla_produccion_fecha` (
  `idTabla_Produccion` INT(11) NOT NULL,
  `Fecha_de_Produccion` DATE NOT NULL,
  PRIMARY KEY (`idTabla_Produccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`salida_mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`salida_mercancia` (
  `idSalida_Mercancia` INT(11) NOT NULL,
  `Cantidad_Salida` INT(11) NULL DEFAULT NULL,
  `Productos_idProductos` INT(11) NOT NULL,
  `Tabla_Produccion_Fecha_idTabla_Produccion` INT(11) NOT NULL,
  `Sucursales_idSucursales` INT(11) NOT NULL,
  PRIMARY KEY (`idSalida_Mercancia`, `Tabla_Produccion_Fecha_idTabla_Produccion`, `Sucursales_idSucursales`, `Productos_idProductos`),
  INDEX `fk_Salida_Mercancia_Productos1_idx` (`Productos_idProductos` ASC) ,
  INDEX `fk_Salida_Mercancia_Tabla_Produccion_Fecha1_idx` (`Tabla_Produccion_Fecha_idTabla_Produccion` ASC) ,
  INDEX `fk_Salida_Mercancia_Sucursales1_idx` (`Sucursales_idSucursales` ASC) ,
  CONSTRAINT `fk_Salida_Mercancia_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salida_Mercancia_Sucursales1`
    FOREIGN KEY (`Sucursales_idSucursales`)
    REFERENCES `basepanav3`.`sucursales` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salida_Mercancia_Tabla_Produccion_Fecha1`
    FOREIGN KEY (`Tabla_Produccion_Fecha_idTabla_Produccion`)
    REFERENCES `basepanav3`.`tabla_produccion_fecha` (`idTabla_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`mercancia_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`mercancia_sucursal` (
  `idPedidos` INT(11) NOT NULL,
  `Confirmacion_Salida` TINYINT(1) NOT NULL,
  `Nota` VARCHAR(150) NULL DEFAULT NULL,
  `Salida_Mercancia_idSalida_Mercancia` INT(11) NOT NULL,
  PRIMARY KEY (`idPedidos`, `Salida_Mercancia_idSalida_Mercancia`),
  UNIQUE INDEX `Salida_Mercancia_idSalida_Mercancia` (`Salida_Mercancia_idSalida_Mercancia` ASC) ,
  INDEX `fk_Mercancia_Sucursal_Salida_Mercancia1_idx` (`Salida_Mercancia_idSalida_Mercancia` ASC) ,
  CONSTRAINT `fk_Mercancia_Sucursal_Salida_Mercancia1`
    FOREIGN KEY (`Salida_Mercancia_idSalida_Mercancia`)
    REFERENCES `basepanav3`.`salida_mercancia` (`idSalida_Mercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`mermas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`mermas` (
  `idSupervision` INT(11) NOT NULL,
  `Conteo_Merma` INT(10) NULL DEFAULT NULL,
  `productos_idProductos` INT(11) NOT NULL,
  `tabla_produccion_fecha_idTabla_Produccion` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idSupervision`, `productos_idProductos`, `tabla_produccion_fecha_idTabla_Produccion`, `users_id`),
  INDEX `fk_mermas_productos1_idx` (`productos_idProductos` ASC) ,
  INDEX `fk_mermas_tabla_produccion_fecha1_idx` (`tabla_produccion_fecha_idTabla_Produccion` ASC) ,
  INDEX `fk_mermas_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_mermas_productos1`
    FOREIGN KEY (`productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_tabla_produccion_fecha1`
    FOREIGN KEY (`tabla_produccion_fecha_idTabla_Produccion`)
    REFERENCES `basepanav3`.`tabla_produccion_fecha` (`idTabla_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `basepanav3`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`migrations` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  `class` VARCHAR(255) NOT NULL,
  `group` VARCHAR(255) NOT NULL,
  `namespace` VARCHAR(255) NOT NULL,
  `time` INT(11) NOT NULL,
  `batch` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`produccion_deseada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`produccion_deseada` (
  `idProduccion_Deseada` INT(11) NOT NULL,
  `Fecha_Registro` DATE NULL DEFAULT NULL,
  `Cantidad_requerida` INT(11) NOT NULL,
  `Productos_idProductos` INT(11) NOT NULL,
  PRIMARY KEY (`idProduccion_Deseada`, `Productos_idProductos`),
  INDEX `fk_Produccion_Deseada_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Produccion_Deseada_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`produccion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`produccion_productos` (
  `idProduccion_Productos` INT(11) NOT NULL,
  `Cantidad_Realizada` INT(11) NOT NULL,
  `Productos_idProductos` INT(11) NOT NULL,
  PRIMARY KEY (`idProduccion_Productos`, `Productos_idProductos`),
  INDEX `fk_Produccion_Productos_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Produccion_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`productos_has_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`productos_has_almacen` (
  `Productos_idProductos` INT(11) NOT NULL,
  `Almacen_idAlmacen` INT(11) NOT NULL,
  `Cantidad_uso` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Almacen_idAlmacen`),
  INDEX `fk_Productos_has_Almacen_Almacen1_idx` (`Almacen_idAlmacen` ASC) ,
  INDEX `fk_Productos_has_Almacen_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Productos_has_Almacen_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `basepanav3`.`almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Almacen_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`settings` (
  `id` INT(9) NOT NULL,
  `class` VARCHAR(255) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(31) NOT NULL DEFAULT 'string',
  `context` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basepanav3`.`tabla_produccion_fecha_has_produccion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`tabla_produccion_fecha_has_produccion_productos` (
  `id` INT(11) NOT NULL,
  `Tabla_Produccion_idTabla_Produccion_Fecha` INT(11) NOT NULL,
  `Produccion_Productos_idProduccion_Productos` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tabla_Produccion_has_Produccion_Productos_Produccion_Pro_idx` (`Produccion_Productos_idProduccion_Productos` ASC) ,
  INDEX `fk_Tabla_Produccion_has_Produccion_Productos_Tabla_Producci_idx` (`Tabla_Produccion_idTabla_Produccion_Fecha` ASC) ,
  CONSTRAINT `fk_Tabla_Produccion_has_Produccion_Productos_Produccion_Produ1`
    FOREIGN KEY (`Produccion_Productos_idProduccion_Productos`)
    REFERENCES `basepanav3`.`produccion_productos` (`idProduccion_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabla_Produccion_has_Produccion_Productos_Tabla_Produccion1`
    FOREIGN KEY (`Tabla_Produccion_idTabla_Produccion_Fecha`)
    REFERENCES `basepanav3`.`tabla_produccion_fecha` (`idTabla_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`ventas` (
  `idVentas` INT(11) NOT NULL,
  `ValorMoneda` INT(11) NULL DEFAULT NULL,
  `mercancia_sucursal_idPedidos` INT(11) NOT NULL,
  PRIMARY KEY (`idVentas`, `mercancia_sucursal_idPedidos`),
  INDEX `fk_ventas_mercancia_sucursal1_idx` (`mercancia_sucursal_idPedidos` ASC) ,
  CONSTRAINT `fk_ventas_mercancia_sucursal1`
    FOREIGN KEY (`mercancia_sucursal_idPedidos`)
    REFERENCES `basepanav3`.`mercancia_sucursal` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `basepanav3`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basepanav3`.`Pedidos` (
  `idPedidos` INT(11) NOT NULL,
  `Nombre_Cliente` VARCHAR(45) NULL,
  `Fecha_Pedido` DATE NOT NULL,
  `Cantidad_requerida` INT(11) NOT NULL,
  `Productos_idProductos` INT(11) NOT NULL,
  PRIMARY KEY (`idPedidos`, `Productos_idProductos`),
  INDEX `fk_Produccion_Deseada_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Produccion_Deseada_Productos10`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `basepanav3`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
