-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 11:11:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema panaderia_modelo_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema panaderia_modelo_v2
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `panaderia_modelo_v2` DEFAULT CHARACTER SET utf8 ;
USE `panaderia_modelo_v2` ;

-- -----------------------------------------------------
-- Table `panaderia_nueva`.`Provedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Provedores` (
  `idProvedores` INT NOT NULL AUTO_INCREMENT,
  `Nombre_provedor` VARCHAR(80) NOT NULL,
  `Producto` VARCHAR(80) NOT NULL,
  `Telefono` INT NOT NULL,
  `Telefono_opcional` INT NULL,
  PRIMARY KEY (`idProvedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Referencias_Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Referencias_Almacen` (
  `idReferencias_Almacen` INT NOT NULL AUTO_INCREMENT,
  `Medida` VARCHAR(45) NULL,
  `Cantidad_medida` DECIMAL NULL,
  `Tipo_medicion` VARCHAR(20) NULL,
  `Provedores_idProvedores` INT NOT NULL,
  PRIMARY KEY (`idReferencias_Almacen`, `Provedores_idProvedores`),
  INDEX `fk_Referencias_Almacen_Provedores1_idx` (`Provedores_idProvedores` ASC) ,
  CONSTRAINT `fk_Referencias_Almacen_Provedores1`
    FOREIGN KEY (`Provedores_idProvedores`)
    REFERENCES `panaderia_modelo_v2`.`Provedores` (`idProvedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Cantidad_Existente` DECIMAL NOT NULL,
  `Cantidad_Minimas` DECIMAL NOT NULL,
  `imagen_ref` VARCHAR(200) NULL,
  `Referencias_Almacen_idReferencias_Almacen` INT NOT NULL,
  PRIMARY KEY (`idAlmacen`, `Referencias_Almacen_idReferencias_Almacen`),
  INDEX `fk_Almacen_Referencias_Almacen1_idx` (`Referencias_Almacen_idReferencias_Almacen` ASC) ,
  CONSTRAINT `fk_Almacen_Referencias_Almacen1`
    FOREIGN KEY (`Referencias_Almacen_idReferencias_Almacen`)
    REFERENCES `panaderia_modelo_v2`.`Referencias_Almacen` (`idReferencias_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Incremento_Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Incremento_Almacen` (
  `idIncremento_Almacen` INT NOT NULL AUTO_INCREMENT,
  `Fecha_de_Ingreso` DATE NOT NULL,
  `Cantidad_Ingresada` DECIMAL NOT NULL,
  `Almacen_idAlmacen` INT NOT NULL,
  PRIMARY KEY (`idIncremento_Almacen`, `Almacen_idAlmacen`),
  INDEX `fk_Incremento_Almacen_Almacen_idx` (`Almacen_idAlmacen` ASC) ,
  CONSTRAINT `fk_Incremento_Almacen_Almacen`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `panaderia_modelo_v2`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Valor_produccion` DECIMAL NULL,
  `Valor_Venta` DECIMAL NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Tabla_Produccion_Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Tabla_Produccion_Fecha` (
  `idTabla_Produccion` INT NOT NULL AUTO_INCREMENT,
  `Fecha_de_Produccion` DATE NOT NULL,
  PRIMARY KEY (`idTabla_Produccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Produccion_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Produccion_Productos` (
  `idProduccion_Productos` INT NOT NULL AUTO_INCREMENT,
  `Cantidad_Realizada` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idProduccion_Productos`, `Productos_idProductos`),
  INDEX `fk_Produccion_Productos_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Produccion_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `panaderia_modelo_v2`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Tabla_Produccion_Fecha_has_Produccion_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Tabla_Produccion_Fecha_has_Produccion_Productos` (
  `Tabla_Produccion_idTabla_Produccion_Fecha` INT NOT NULL,
  `Produccion_Productos_idProduccion_Productos` INT NOT NULL,
  PRIMARY KEY (`Tabla_Produccion_idTabla_Produccion_Fecha`, `Produccion_Productos_idProduccion_Productos`),
  INDEX `fk_Tabla_Produccion_has_Produccion_Productos_Produccion_Pro_idx` (`Produccion_Productos_idProduccion_Productos` ASC) ,
  INDEX `fk_Tabla_Produccion_has_Produccion_Productos_Tabla_Producci_idx` (`Tabla_Produccion_idTabla_Produccion_Fecha` ASC) ,
  CONSTRAINT `fk_Tabla_Produccion_has_Produccion_Productos_Tabla_Produccion1`
    FOREIGN KEY (`Tabla_Produccion_idTabla_Produccion_Fecha`)
    REFERENCES `panaderia_modelo_v2`.`Tabla_Produccion_Fecha` (`idTabla_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabla_Produccion_has_Produccion_Productos_Produccion_Produ1`
    FOREIGN KEY (`Produccion_Productos_idProduccion_Productos`)
    REFERENCES `panaderia_modelo_v2`.`Produccion_Productos` (`idProduccion_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Productos_has_Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Productos_has_Almacen` (
  `Productos_idProductos` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `Cantidad_uso` DECIMAL NULL,
  PRIMARY KEY (`Productos_idProductos`, `Almacen_idAlmacen`),
  INDEX `fk_Productos_has_Almacen_Almacen1_idx` (`Almacen_idAlmacen` ASC) ,
  INDEX `fk_Productos_has_Almacen_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Productos_has_Almacen_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `panaderia_modelo_v2`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Almacen_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `panaderia_modelo_v2`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(100) NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Numero_Telefonico` INT NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Sucursales` (
  `idSucursales` INT NOT NULL AUTO_INCREMENT,
  `NombreSucursal` VARCHAR(70) NOT NULL,
  `Direccion_Sucursal` VARCHAR(80) NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idSucursales`, `Empleados_idEmpleados`),
  INDEX `fk_Sucursales_Empleados1_idx` (`Empleados_idEmpleados` ASC) ,
  CONSTRAINT `fk_Sucursales_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `panaderia_modelo_v2`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Salida_Mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Salida_Mercancia` (
  `idSalida_Mercancia` INT NOT NULL,
  `Cantidad_Salida` INT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Tabla_Produccion_Fecha_idTabla_Produccion` INT NOT NULL,
  `Sucursales_idSucursales` INT NOT NULL,
  PRIMARY KEY (`idSalida_Mercancia`, `Tabla_Produccion_Fecha_idTabla_Produccion`, `Sucursales_idSucursales`, `Productos_idProductos`),
  INDEX `fk_Salida_Mercancia_Productos1_idx` (`Productos_idProductos` ASC) ,
  INDEX `fk_Salida_Mercancia_Tabla_Produccion_Fecha1_idx` (`Tabla_Produccion_Fecha_idTabla_Produccion` ASC) ,
  INDEX `fk_Salida_Mercancia_Sucursales1_idx` (`Sucursales_idSucursales` ASC) ,
  CONSTRAINT `fk_Salida_Mercancia_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `panaderia_modelo_v2`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salida_Mercancia_Tabla_Produccion_Fecha1`
    FOREIGN KEY (`Tabla_Produccion_Fecha_idTabla_Produccion`)
    REFERENCES `panaderia_modelo_v2`.`Tabla_Produccion_Fecha` (`idTabla_Produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salida_Mercancia_Sucursales1`
    FOREIGN KEY (`Sucursales_idSucursales`)
    REFERENCES `panaderia_modelo_v2`.`Sucursales` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `ValorMoneda` INT NULL,
  PRIMARY KEY (`idVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Mercancia_Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Mercancia_Sucursal` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `Confirmacion_Salida` VARCHAR(45) NOT NULL,
  `Nota` VARCHAR(150) NULL,
  `Salida_Mercancia_idSalida_Mercancia` INT NOT NULL,
  `Ventas_idVentas` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `Salida_Mercancia_idSalida_Mercancia`, `Ventas_idVentas`),
  INDEX `fk_Mercancia_Sucursal_Salida_Mercancia1_idx` (`Salida_Mercancia_idSalida_Mercancia` ASC) ,
  INDEX `fk_Mercancia_Sucursal_Ventas1_idx` (`Ventas_idVentas` ASC) ,
  CONSTRAINT `fk_Mercancia_Sucursal_Salida_Mercancia1`
    FOREIGN KEY (`Salida_Mercancia_idSalida_Mercancia`)
    REFERENCES `panaderia_modelo_v2`.`Salida_Mercancia` (`idSalida_Mercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mercancia_Sucursal_Ventas1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `panaderia_modelo_v2`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Supervision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Supervision` (
  `idSupervision` INT NOT NULL AUTO_INCREMENT,
  `Sucursales_idSucursales` INT NOT NULL,
  `Sucursales_Empleados_idEmpleados` INT NOT NULL,
  `Conteo_Pedido` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupervision`, `Sucursales_idSucursales`, `Sucursales_Empleados_idEmpleados`),
  INDEX `fk_Supervision_Sucursales1_idx` (`Sucursales_idSucursales` ASC, `Sucursales_Empleados_idEmpleados` ASC) ,
  CONSTRAINT `fk_Supervision_Sucursales1`
    FOREIGN KEY (`Sucursales_idSucursales`)
    REFERENCES `panaderia_modelo_v2`.`Sucursales` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`corroborar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`corroborar` (
  `idcorroborar` INT NOT NULL AUTO_INCREMENT,
  `Fecha_edicion` DATE NOT NULL,
  `Cantidad_cambio_Existente` DECIMAL NOT NULL,
  `Cantidad_Existente_Sistema` DECIMAL NOT NULL,
  `Almacen_idAlmacen` INT NOT NULL,
  `Almacen_Referencias_Almacen_idReferencias_Almacen` INT NOT NULL,
  PRIMARY KEY (`idcorroborar`, `Almacen_idAlmacen`, `Almacen_Referencias_Almacen_idReferencias_Almacen`),
  INDEX `fk_corroborar_Almacen1_idx` (`Almacen_idAlmacen` ASC, `Almacen_Referencias_Almacen_idReferencias_Almacen` ASC) ,
  CONSTRAINT `fk_corroborar_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen` , `Almacen_Referencias_Almacen_idReferencias_Almacen`)
    REFERENCES `panaderia_modelo_v2`.`Almacen` (`idAlmacen` , `Referencias_Almacen_idReferencias_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panaderia_modelo_v2`.`Produccion_Deseada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panaderia_modelo_v2`.`Produccion_Deseada` (
  `idProduccion_Deseada` INT NOT NULL,
  `Fecha_Registro` DATE NULL,
  `Cantidad_requerida` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idProduccion_Deseada`, `Productos_idProductos`),
  INDEX `fk_Produccion_Deseada_Productos1_idx` (`Productos_idProductos` ASC) ,
  CONSTRAINT `fk_Produccion_Deseada_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `panaderia_modelo_v2`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
